[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.develop]
  command = "npm run build"
  
[context.branch-deploy]
  command = "npm run build" 